[tool:pytest]
addopts = -v --cov=. --cov-report=html --cov-report=term-missing
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings = ignore::DeprecationWarning